language: go
go:
  - 1.6
  - tip
before-install:
  - composer self-update
install:
  - go get github.com/gorilla/mux
  - go get github.com/golang/glog
  - gem install sass
  - bower install
  - npm install
script:
  - gulp bower
  - gulp
